server:
  port: 8000
spring:
  application:
    name: microservice-provider-pms    # 项目名称尽量用小写

eureka:
  client:
    serviceUrl:
      defaultZone: http://discovery:8761/eureka/    # 指定注册中心的地址
  instance:
    preferIpAddress: true